# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bg1G996lwg4hh8TjghbEXD-N43HsO9hE

Meet Dr. Ignaz Semmelweis
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

import io
yearly = pd.read_csv(io.BytesIO(uploaded['yearly_deaths_by_clinic.csv']))

yearly

"""The alarming number of deaths"""

yearly['proportion_deaths'] = yearly.deaths.divide(yearly.births)
yearly1 = yearly[yearly.clinic == 'clinic 1']
yearly2 = yearly[yearly.clinic == 'clinic 2']
yearly1

"""Death at the clinics"""

import matplotlib.pyplot as plt

ax=yearly1.plot(x='proportion_deaths',y='year',label='yearly1')
yearly2.plot(x='proportion_deaths',y='year',label='yearly2',ax=ax)

"""The handwashing begins"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
monthly = pd.read_csv(io.BytesIO(uploaded['monthly_deaths.csv']))

monthly['proportion_deaths'] = monthly.deaths.divide(monthly.births)
monthly.head()

"""The effect of handwashing"""

import matplotlib.pyplot as plt
ax=monthly.plot(x='date',y='proportion_deaths')

"""The effect of handwashing highlighted"""

import pandas as pd
handwashing_start = pd.to_datetime('1847-06-01')

before_washing = monthly[monthly.date < handwashing_start]
after_washing = monthly[monthly.date >= handwashing_start]

ax = before_washing.plot(x='date', y='proportion_deaths', label='Before handwashing')
after_washing.plot(x='date', y='proportion_deaths', label='After handwashing', ax=ax)
ax.set_ylabel('Proportion deaths')

"""More handwashing, fewer deaths?"""

before_proportion = before_washing.proportion_deaths
after_proportion = after_washing.proportion_deaths
mean_diff = after_proportion.mean() - before_proportion.mean() 
print(mean_diff)

"""A Bootstrap analysis of Semmelweis handwashing data"""

from numpy import percentile
boot_mean_diff = []
for i in range(3000):
    boot_before = before_proportion.sample(frac=1, replace=True)
    boot_after = after_proportion.sample(frac=1, replace=True)
    boot_mean_diff.append(boot_after.mean() - boot_before.mean())

 
confidence_interval = percentile(boot_mean_diff, [2.5, 97.5])
print(confidence_interval)

"""The fate of Dr. Semmelweis"""

doctors_should_wash_their_hands = True